### PR TITLE
fix: script action parse output from Task API

### LINKED ISSUE #15135: set-teamsfx-env does not expand variables
**Describe the bug**
I'm using a script to gather the current user principal to send it to the bicep template like this:

```yaml
  - uses: script
    name: set environment variables
    with:
      run: $AZURE_PRINCIPAL_ID=(az ad signed-in-user show --query id -o tsv);
        echo "::set-teamsfx-env
        AZURE_PRINCIPAL_ID=${AZURE_PRINCIPAL_ID}"
```

When I run it I can see in the output the correct ID:

```shell
*  Executing task: $AZURE_PRINCIPAL_ID=(az ad signed-in-user show --query id -o tsv); echo $AZURE_PRINCIPAL_ID; echo "::set-teamsfx-env AZURE_PRINCIPAL_ID=${AZURE_PRINCIPAL_ID}" 

::set-teamsfx-env
AZURE_PRINCIPAL_ID=ee******-****-****-****-********46e9
 *  Terminal will be reused by tasks, press any key to close it. 
```

But then, in the .env.dev file, the unexpanded value is stored:

```env
AZURE_PRINCIPAL_ID=${AZURE_PRINCIPAL_ID}
```

**To Reproduce**
1. Write a script
2. Store a value inside a script variable (ex: `$VAR="value"`)
3. Use echo "::set-teamsfx-env ..." to write the variable to the environment
4. See the unexpanded variable in the .env.dev file

**Expected behavior**
Write expanded value into the .env file

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 6.4.2

**CLI Information (please complete the following information):**
 - OS: Windows

**Additional context**

Script is running on powershell

### PR DESCRIPTION
**Pull request by tecton**
Fix #15135

### CODE REVIEW

File: packages/cli/src/userInteraction.ts [hunk 1]
```diff
@@ -641,15 +641,22 @@ class CLIUserInteraction implements UserInteraction {
       const command = isWindows ? "cmd.exe" : "/bin/bash";
       const commandArgs = isWindows ? ["/c", args.cmd] : ["-c", args.cmd];
       logger.info(`Executing task: ${args.cmd}`);
+      let output = "";
       const childProcess = spawn(command, commandArgs, {
-        stdio: "inherit",
+        stdio: ["inherit", "pipe", "pipe"],
```
Comment (HuihuiWu-Microsoft) [inline packages/cli/src/userInteraction.ts:646]: what's the difference with the added two?

Comment (tecton) [reply packages/cli/src/userInteraction.ts:646]: They are used for stdout and stderr that we can capture the actual script output string.

**Review by HuihuiWu-Microsoft — APPROVED** [review]

**Review by Alive-Fish — APPROVED** [review]
